### ISSUE TITLE
想用您的数据做个脏话生成网站

### ISSUE THREAD

**Issue by manakanemu** [pokemonchw/Dirty#2]
和骂人宝典类似，但是打算加入用emoji替换敏感词，防屏蔽的功能

**Comment by pokemonchw** [comment]
这个repo,是为了,反网络暴力而建立的,同时我也一直有被用于网络暴力的担忧...你看,果然应验了,甚至给我发了issue...
唉

**Comment by manakanemu** [comment]
> 这个repo,是为了,反网络暴力而建立的,同时我也一直有被用于网络暴力的担忧...你看,果然应验了,甚至给我发了issue...
> 唉

您误会了，事实上我写这个网站的目的也是为了那些不会骂人的人，只不过现在国内各种发言场所屏蔽算法四起，骂人者已经懂得使用emoji，而受害者却还无法武装自己，所以我才想做这个网站，事实上，某种程度上这出于我的自身经历。

**Comment by pokemonchw** [comment]
我觉得可以,需要注意的是,由于我没有做反对商业用途的限制,并且这个项目已经挂上了mit协议,所以有一条是,需要注明数据来源,或者像我md里那样,注明部分数据来源于这里,另一方面是,希望能够提供一部分处理过后的数据,用于语料训练的工作,感激不尽
